### ISSUE TITLE
Bucket Deletion Failing

### ISSUE THREAD

**Issue by mattgagliardi** [mulbc/gosbench#11]
I'm consistently receiving this message as my test runs end:

`Error during bucket deleting - ignoring       error="BatchedDeleteIncomplete: some objects have failed to be deleted.\ncaused by: failed to perform batch operation on \"\" to \"\":\nNoSuchBucket: The specified bucket does not exist\n\tstatus code: 404, request id: 167E6C0CDDE87D15, host id: "`

Not really sure why.  Sometimes the bucket does remain on my storage system (when that error is repeated 10 times), other times there are fewer than 10 of those entries and the bucket is gone.

**Comment by mulbc** [comment]
I think this is just a race condition during deleting that you can probably ignore. Important here is that the bucket is gone at the end.
