### ISSUE TITLE
object is wrong for fuc EvaluateDistribution

### ISSUE THREAD

**Issue by thenamehasbeentake** [mulbc/gosbench#17]
**Describe the bug**
When config objects `number_distribution: sequential` and `number_min: 1`, only 1 object writes many times

**To Reproduce**
Only fill 1 op  when `number_distribution` is `sequential` from `number_min` value 1
https://github.com/mulbc/gosbench/blob/d9e82dc1c4edac1bd5655e7f1354696c87026e29/worker/main.go#L258

**Expected behavior**
Obj name should increment from `number_min`  to `number_max`

Func common.EvaluateDistribution shouldn't means bucketCount and bucket should not start from uint64(0).
`fillWorkqueue` to fill works in the test in advance and then `workUntilTimeout` seems logically inaccurate

**Comment by mulbc** [comment]
Closing - the function works as expected. There is no guarantee that the object name starts with number_min and goes up to number_max. While I can understand the desire to do this for sequential runs, it wouldn't work well with other distributions like random.
